import { Option } from 'payload'

const VIETNAM_PROVINCES: Option[] = [
  { label: 'An Giang', value: 'AG' },
  { label: 'Bà Rịa - Vũng Tàu', value: 'BR-VT' },
  { label: 'Bắc Giang', value: 'BG' },
  { label: 'Bắc Kạn', value: 'BK' },
  { label: 'Bạc Liêu', value: 'BL' },
  { label: 'Bắc Ninh', value: 'BN' },
  { label: 'Bến Tre', value: 'BTR' },
  { label: 'Bình Dương', value: 'BDUOG' },
  { label: 'Bình Định', value: 'BDINH' },
  { label: 'Bình Phước', value: 'BP' },
  { label: 'Bình Thuận', value: 'BTN' },
  { label: 'Cà Mau', value: 'CM' },
  { label: 'Cần Thơ', value: 'CT' },
  { label: 'Cao Bằng', value: 'CB' },
  { label: 'Đà Nẵng', value: 'DN' },
  { label: 'Đắk Lắk', value: 'DALAT' },
  { label: 'Đắk Nông', value: 'DNONG' },
  { label: 'Điện Biên', value: 'DBIEN' },
  { label: 'Đồng Nai', value: 'DNAI' },
  { label: 'Đồng Tháp', value: 'DTHAP' },
  { label: 'Gia Lai', value: 'GL' },
  { label: 'Hà Giang', value: 'HAG' },
  { label: 'Hà Nam', value: 'HAN' },
  { label: 'Hà Nội', value: 'HN' },
  { label: 'Hà Tĩnh', value: 'HT' },
  { label: 'Hải Dương', value: 'HD' },
  { label: 'Hải Phòng', value: 'HP' },
  { label: 'Hậu Giang', value: 'HGI' },
  { label: 'Hòa Bình', value: 'HB' },
  { label: 'Hồ Chí Minh', value: 'HCM' },
  { label: 'Hưng Yên', value: 'HY' },
  { label: 'Khánh Hòa', value: 'KH' },
  { label: 'Kiên Giang', value: 'KG' },
  { label: 'Kon Tum', value: 'KT' },
  { label: 'Lai Châu', value: 'LCH' },
  { label: 'Lâm Đồng', value: 'LD' },
  { label: 'Lạng Sơn', value: 'LS' },
  { label: 'Lào Cai', value: 'LCA' },
  { label: 'Long An', value: 'LA' },
  { label: 'Nam Định', value: 'NAMD' },
  { label: 'Nghệ An', value: 'NA' },
  { label: 'Ninh Bình', value: 'NB' },
  { label: 'Ninh Thuận', value: 'NT' },
  { label: 'Phú Thọ', value: 'PT' },
  { label: 'Phú Yên', value: 'PY' },
  { label: 'Quảng Bình', value: 'QB' },
  { label: 'Quảng Nam', value: 'QNA' },
  { label: 'Quảng Ngãi', value: 'QNg' },
  { label: 'Quảng Ninh', value: 'QNI' },
  { label: 'Quảng Trị', value: 'QT' },
  { label: 'Sóc Trăng', value: 'ST' },
  { label: 'Sơn La', value: 'SL' },
  { label: 'Tây Ninh', value: 'TNINH' },
  { label: 'Thái Bình', value: 'TB' },
  { label: 'Thái Nguyên', value: 'TNG' },
  { label: 'Thanh Hóa', value: 'TH' },
  { label: 'Thừa Thiên-Huế', value: 'TTH' },
  { label: 'Tiền Giang', value: 'TG' },
  { label: 'Trà Vinh', value: 'TV' },
  { label: 'Tuyên Quang', value: 'TQ' },
  { label: 'Vĩnh Long', value: 'VL' },
  { label: 'Vĩnh Phúc', value: 'VP' },
  { label: 'Yên Bái', value: 'YB' },
]

export { VIETNAM_PROVINCES }
