const USERS = [
  {
    id: 1,
    email: 'bot@email.com',
    password: 'Bot@123',
    role: 'super_admin',
    date_of_birth: '2003-12-30',
    phone_number: '0999999999',
  },
  {
    id: 2,
    email: 'nguyen@email.com',
    password: 'Nguyen@123',
    role: 'super_admin',
    date_of_birth: '2003-12-30',
    phone_number: '0944755822',
  },
  {
    id: 3,
    email: 'nhu@email.com',
    password: 'Nhu@123',
    role: 'admin',
    date_of_birth: '2003-01-01',
    phone_number: '0369951061',
  },
  {
    id: 4,
    email: 'nhan@email.com',
    password: 'Nhan@123',
    role: 'user',
    date_of_birth: '2003-01-01',
    phone_number: '0353963753',
  },
]

const PAYMENT_STATUSES = ['Waiting for payment', 'Success', 'Failed']

const PAYMENT_METHODS = [
  { name: 'Credit Card', active: true },
  { name: 'Cash', active: true },
]

const SIZES = [
  { label: 'XS', description: 'Extra Small, smaller than the usual sizes.' },
  { label: 'S', description: 'Small, slightly smaller than the standard size.' },
  { label: 'M', description: 'Medium, a standard size suitable for most body types.' },
  { label: 'L', description: 'Large, larger than the usual size.' },
  { label: 'XL', description: 'Extra Large, much larger than the standard size.' },
  { label: 'XXL', description: 'Extra Extra Large, significantly larger than Extra Large.' },
  { label: 'XXXL', description: 'Extra Extra Extra Large, extremely large.' },
]

const COLORS = [
  { label: 'Red', description: 'A bright and bold color' },
  { label: 'Green', description: 'A color representing nature' },
  { label: 'Blue', description: 'A calm and cool color' },
  { label: 'Yellow', description: 'A bright and cheerful color' },
  { label: 'Orange', description: 'A vibrant and energetic color' },
  { label: 'Purple', description: 'A royal and luxurious color' },
  { label: 'Pink', description: 'A soft and playful color' },
  { label: 'Black', description: 'A strong and powerful color' },
  { label: 'White', description: 'A pure and clean color' },
  { label: 'Gray', description: 'A neutral and balanced color' },
  { label: 'Brown', description: 'A warm and earthy color' },
  { label: 'Cyan', description: 'A bright and refreshing color' },
  { label: 'Magenta', description: 'A bold and vibrant color' },
  { label: 'Lime', description: 'A bright and zesty color' },
  { label: 'Teal', description: 'A calm and sophisticated color' },
  { label: 'Indigo', description: 'A deep and rich color' },
  { label: 'Violet', description: 'A soft and romantic color' },
  { label: 'Maroon', description: 'A deep and warm color' },
  { label: 'Olive', description: 'A natural and earthy color' },
  { label: 'Navy', description: 'A strong and reliable color' },
  { label: 'Gold', description: 'A luxurious and rich color' },
  { label: 'Silver', description: 'A sleek and modern color' },
  { label: 'Beige', description: 'A soft and neutral color' },
  { label: 'Peach', description: 'A warm and inviting color' },
  { label: 'Turquoise', description: 'A bright and tropical color' },
  { label: 'Mint', description: 'A fresh and cool color' },
  { label: 'Lavender', description: 'A soft and calming color' },
  { label: 'Coral', description: 'A warm and lively color' },
  { label: 'Salmon', description: 'A soft and warm color' },
  { label: 'Khaki', description: 'A neutral and earthy color' },
  { label: 'Crimson', description: 'A deep and passionate color' },
  { label: 'Azure', description: 'A bright and clear color' },
  { label: 'Amethyst', description: 'A rich and luxurious color' },
  { label: 'Plum', description: 'A deep and rich color' },
  { label: 'Saffron', description: 'A warm and exotic color' },
  { label: 'Charcoal', description: 'A strong and neutral color' },
  { label: 'Ivory', description: 'A soft and elegant color' },
  { label: 'Periwinkle', description: 'A soft and whimsical color' },
  { label: 'Scarlet', description: 'A bold and passionate color' },
  { label: 'Emerald', description: 'A rich and vibrant color' },
  { label: 'Rust', description: 'A warm and earthy color' },
  { label: 'Tan', description: 'A soft and neutral color' },
  { label: 'Burgundy', description: 'A deep and rich color' },
  { label: 'Ochre', description: 'A warm and earthy color' },
  { label: 'Ruby', description: 'A rich and vibrant color' },
  { label: 'Onyx', description: 'A strong and powerful color' },
  { label: 'Sand', description: 'A soft and neutral color' },
  { label: 'Steel', description: 'A strong and modern color' },
]

// Clothes Categories
const CLOTHES_CATEGORIES = [
  {
    name: 'Shirts',
    slug: 'shirts',
    description: 'Various styles of shirts for men and women',
  },
  {
    name: 'Pants',
    slug: 'pants',
    description: 'Different types of pants including jeans, trousers, and shorts',
  },
  {
    name: 'Dresses',
    slug: 'dresses',
    description: 'A variety of dresses for different occasions',
  },
  {
    name: 'Outerwear',
    slug: 'outerwear',
    description: 'Jackets, coats, and other outerwear',
  },
  {
    name: 'Footwear',
    slug: 'footwear',
    description: 'Shoes, sandals, and other types of footwear',
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Hats, belts, scarves, and other accessories',
  },
  {
    name: 'Activewear',
    slug: 'activewear',
    description: 'Clothing for sports and other physical activities',
  },
  {
    name: 'Underwear',
    slug: 'underwear',
    description: 'Various types of underwear for men and women',
  },
  {
    name: 'Swimwear',
    slug: 'swimwear',
    description: 'Swimsuits and other swimwear',
  },
  {
    name: 'Sleepwear',
    slug: 'sleepwear',
    description: 'Pajamas and other sleepwear',
  },
]

const COUPONS = [
  // Existing coupons
  {
    code: 'SUMMER2023',
    discount_type: 'percentage',
    description: 'Get 20% off on all summer items',
    discount: 20,
    start_date: '2024-10-01',
    end_date: '2024-12-30',
    quantity: 100,
    minimum_price_to_use: 100,
  },
  {
    code: 'FREESHIP50',
    discount_type: 'fixed_amount',
    description: 'Free shipping on orders over $50',
    discount: 50,
    start_date: '2024-10-01',
    end_date: '2025-02-10',
    quantity: 100,
    minimum_price_to_use: 50,
  },
  {
    code: 'HOLIDAY24',
    discount_type: 'percentage',
    description: '25% off holiday collection',
    discount: 25,
    start_date: '2024-11-15',
    end_date: '2024-12-25',
    quantity: 200,
    minimum_price_to_use: 75,
  },
  {
    code: 'BUNDLE100',
    discount_type: 'fixed_amount',
    description: '$100 off on purchases above $500',
    discount: 100,
    start_date: '2024-10-01',
    end_date: '2025-01-31',
    quantity: 50,
    minimum_price_to_use: 500,
  },
  {
    code: 'FLASH30',
    discount_type: 'percentage',
    description: 'Flash sale: 30% off for 48 hours',
    discount: 30,
    start_date: '2024-12-15',
    end_date: '2024-12-17',
    quantity: 75,
    minimum_price_to_use: 150,
  },
  {
    code: '15OFFALLPRODUCTS',
    discount_type: 'percentage',
    description: '15% off your purchase',
    discount: 15,
    start_date: '2024-10-01',
    end_date: '2025-03-31',
    quantity: 300,
    minimum_price_to_use: 25,
  },
  {
    code: 'CLEARANCE50',
    discount_type: 'percentage',
    description: '50% off clearance items',
    discount: 50,
    start_date: '2024-12-26',
    end_date: '2025-01-15',
    quantity: 150,
    minimum_price_to_use: 0,
  },
  {
    code: 'BLACKFRI40',
    discount_type: 'percentage',
    description: 'Black Friday special: 40% off storewide',
    discount: 40,
    start_date: '2024-11-24',
    end_date: '2024-11-27',
    quantity: 500,
    minimum_price_to_use: 200,
  },
  {
    code: 'MONDAY20',
    discount_type: 'percentage',
    description: 'Monday Madness: 20% off all items',
    discount: 20,
    start_date: '2024-12-25',
    end_date: '2025-01-31',
    quantity: 150,
    minimum_price_to_use: 100,
  },
  {
    code: 'WEEKEND15',
    discount_type: 'percentage',
    description: '15% off on weekend purchases',
    discount: 15,
    start_date: '2024-12-16',
    end_date: '2025-02-16',
    quantity: 200,
    minimum_price_to_use: 75,
  },

  // Additional 10 coupons
  {
    code: 'WEDDISCOUNT25',
    discount_type: 'percentage',
    description: '25% off every Wednesday',
    discount: 25,
    start_date: '2024-10-01',
    end_date: '2025-03-31',
    quantity: 120,
    minimum_price_to_use: 50,
  },
  {
    code: 'SUNFUN10',
    discount_type: 'fixed_amount',
    description: 'Get $10 off on Sundays',
    discount: 10,
    start_date: '2024-12-01',
    end_date: '2025-02-28',
    quantity: 300,
    minimum_price_to_use: 30,
  },
  {
    code: 'THURSDAY50',
    discount_type: 'percentage',
    description: 'Exclusive 50% off every Thursday',
    discount: 50,
    start_date: '2024-12-01',
    end_date: '2025-03-31',
    quantity: 100,
    minimum_price_to_use: 150,
  },
  {
    code: 'FRINIGHT20',
    discount_type: 'percentage',
    description: '20% off Friday night shopping (6 PM to 12 AM)',
    discount: 20,
    start_date: '2024-12-15',
    end_date: '2025-02-15',
    quantity: 80,
    minimum_price_to_use: 50,
  },
  {
    code: 'NEWYEARS15',
    discount_type: 'percentage',
    description: '15% off on New Year’s Day only',
    discount: 15,
    start_date: '2025-01-01',
    end_date: '2025-01-01',
    quantity: 250,
    minimum_price_to_use: 0,
  },
  {
    code: 'XMAS30',
    discount_type: 'percentage',
    description: '30% off on Christmas Day',
    discount: 30,
    start_date: '2024-12-25',
    end_date: '2024-12-25',
    quantity: 400,
    minimum_price_to_use: 50,
  },
  {
    code: 'SAT50OFF',
    discount_type: 'fixed_amount',
    description: 'Save $50 on Saturdays for orders above $200',
    discount: 50,
    start_date: '2024-12-01',
    end_date: '2025-03-01',
    quantity: 100,
    minimum_price_to_use: 200,
  },
  {
    code: 'MIDWEEK40',
    discount_type: 'percentage',
    description: '40% off mid-week (Wednesday)',
    discount: 40,
    start_date: '2024-10-01',
    end_date: '2025-03-31',
    quantity: 60,
    minimum_price_to_use: 100,
  },
  {
    code: 'FRIDAYFREESHIP',
    discount_type: 'fixed_amount',
    description: 'Free shipping every Friday',
    discount: 10,
    start_date: '2024-12-01',
    end_date: '2025-03-31',
    quantity: 500,
    minimum_price_to_use: 0,
  },
  {
    code: 'LUNARNEWYEAR20',
    discount_type: 'percentage',
    description: '20% off during Lunar New Year',
    discount: 20,
    start_date: '2025-02-08',
    end_date: '2025-02-09',
    quantity: 200,
    minimum_price_to_use: 75,
  },
]

export { PAYMENT_METHODS, COLORS, PAYMENT_STATUSES, CLOTHES_CATEGORIES, SIZES, USERS, COUPONS }
