import { isAdmin } from '@/payload-roles'
import type { CollectionConfig } from 'payload'

export const Colors: CollectionConfig = {
  slug: 'colors',
  access: {
    create: isAdmin,
    read: () => true,
    update: isAdmin,
    delete: isAdmin,
  },
  admin: {
    useAsTitle: 'name',
  },
  fields: [
    {
      name: 'description',
      label: 'Description',
      type: 'textarea',
    },
    {
      name: 'name',
      label: 'Name',
      type: 'select',
      hasMany: true,
      options: [
        { label: 'Red', value: 'red' },
        { label: 'Green', value: 'green' },
        { label: 'Blue', value: 'blue' },
        { label: 'Yellow', value: 'yellow' },
        { label: 'Orange', value: 'orange' },
        { label: 'Purple', value: 'purple' },
        { label: 'Pink', value: 'pink' },
        { label: 'Black', value: 'black' },
        { label: 'White', value: 'white' },
        { label: 'Gray', value: 'gray' },
        { label: 'Brown', value: 'brown' },
        { label: 'Cyan', value: 'cyan' },
        { label: 'Magenta', value: 'magenta' },
        { label: 'Lime', value: 'lime' },
        { label: 'Teal', value: 'teal' },
        { label: 'Indigo', value: 'indigo' },
        { label: 'Violet', value: 'violet' },
        { label: 'Maroon', value: 'maroon' },
        { label: 'Olive', value: 'olive' },
        { label: 'Navy', value: 'navy' },
        { label: 'Gold', value: 'gold' },
        { label: 'Silver', value: 'silver' },
        { label: 'Beige', value: 'beige' },
        { label: 'Peach', value: 'peach' },
        { label: 'Turquoise', value: 'turquoise' },
        { label: 'Mint', value: 'mint' },
        { label: 'Lavender', value: 'lavender' },
        { label: 'Coral', value: 'coral' },
        { label: 'Salmon', value: 'salmon' },
        { label: 'Khaki', value: 'khaki' },
        { label: 'Crimson', value: 'crimson' },
        { label: 'Azure', value: 'azure' },
        { label: 'Amethyst', value: 'amethyst' },
        { label: 'Plum', value: 'plum' },
        { label: 'Saffron', value: 'saffron' },
        { label: 'Charcoal', value: 'charcoal' },
        { label: 'Ivory', value: 'ivory' },
        { label: 'Periwinkle', value: 'periwinkle' },
        { label: 'Scarlet', value: 'scarlet' },
        { label: 'Emerald', value: 'emerald' },
        { label: 'Rust', value: 'rust' },
        { label: 'Tan', value: 'tan' },
        { label: 'Burgundy', value: 'burgundy' },
        { label: 'Ochre', value: 'ochre' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'Onyx', value: 'onyx' },
        { label: 'Sand', value: 'sand' },
        { label: 'Steel', value: 'steel' },
      ],
      admin: {
        isSortable: true,
        position: 'sidebar',
      },
      required: true,
    },
  ],
}
