/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    products: Product;
    variants: Variant;
    product_discounts: ProductDiscount;
    orders: Order;
    order_details: OrderDetail;
    order_trackings: OrderTracking;
    coupons: Coupon;
    comments: Comment;
    addresses: Address;
    order_statuses: OrderStatus;
    colors: Color;
    sizes: Size;
    payments: Payment;
    payment_methods: PaymentMethod;
    payment_statuses: PaymentStatus;
    categories: Category;
    media: Media;
    product_embeddings: ProductEmbedding;
    image_embeddings: ImageEmbedding;
    conversations: Conversation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    product_discounts: ProductDiscountsSelect<false> | ProductDiscountsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    order_details: OrderDetailsSelect<false> | OrderDetailsSelect<true>;
    order_trackings: OrderTrackingsSelect<false> | OrderTrackingsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    order_statuses: OrderStatusesSelect<false> | OrderStatusesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    sizes: SizesSelect<false> | SizesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    payment_methods: PaymentMethodsSelect<false> | PaymentMethodsSelect<true>;
    payment_statuses: PaymentStatusesSelect<false> | PaymentStatusesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    product_embeddings: ProductEmbeddingsSelect<false> | ProductEmbeddingsSelect<true>;
    image_embeddings: ImageEmbeddingsSelect<false> | ImageEmbeddingsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  avatar?: (number | null) | Media;
  role: 'super_admin' | 'admin' | 'user';
  date_of_birth: string;
  phone_number?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description?: string | null;
  visible?: boolean | null;
  price: number;
  overview?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  material?: string | null;
  instruction?: string | null;
  slug: string;
  sold_number?: number | null;
  category?: (number | null) | Category;
  variants?: (number | Variant)[] | null;
  colors?: (number | Color)[] | null;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  product_discounts?: (number | ProductDiscount)[] | null;
  product_reviews?: (number | Comment)[] | null;
  product_embedding?: (number | null) | ProductEmbedding;
  product_image_embeddings?: (number | ImageEmbedding)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Categories for products that are used to group products together
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  category_parent?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  quantity: number;
  size?: (number | null) | Size;
  color?: (number | null) | Color;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes".
 */
export interface Size {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Colors for products that are used to group products together
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  name: string;
  description?: string | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_discounts".
 */
export interface ProductDiscount {
  id: number;
  name: string;
  description?: string | null;
  start_date: string;
  end_date: string;
  discount_type: string;
  discount_value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Comments for products that are conducted by customers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  comment: string;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_embeddings".
 */
export interface ProductEmbedding {
  id: number;
  product_id: string;
  product_embedding: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_embeddings".
 */
export interface ImageEmbedding {
  id: number;
  product_id: string;
  image_embedding: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  total_price: number;
  total_discount: number;
  final_price: number;
  shipping_fee: number;
  buyer: number | User;
  current_status: number | OrderStatus;
  dilivery_address: number | Address;
  order_tracking: number | OrderTracking;
  used_coupon?: (number | null) | Coupon;
  order_details?: (number | OrderDetail)[] | null;
  order_trackings?: (number | OrderTracking)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_statuses".
 */
export interface OrderStatus {
  id: number;
  status: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  name: string;
  province?:
    | (
        | 'AG'
        | 'BR-VT'
        | 'BG'
        | 'BK'
        | 'BL'
        | 'BN'
        | 'BTR'
        | 'BDUOG'
        | 'BDINH'
        | 'BP'
        | 'BTN'
        | 'CM'
        | 'CT'
        | 'CB'
        | 'DN'
        | 'DALAT'
        | 'DNONG'
        | 'DBIEN'
        | 'DNAI'
        | 'DTHAP'
        | 'GL'
        | 'HAG'
        | 'HAN'
        | 'HN'
        | 'HT'
        | 'HD'
        | 'HP'
        | 'HGI'
        | 'HB'
        | 'HCM'
        | 'HY'
        | 'KH'
        | 'KG'
        | 'KT'
        | 'LCH'
        | 'LD'
        | 'LS'
        | 'LCA'
        | 'LA'
        | 'NAMD'
        | 'NA'
        | 'NB'
        | 'NT'
        | 'PT'
        | 'PY'
        | 'QB'
        | 'QNA'
        | 'QNg'
        | 'QNI'
        | 'QT'
        | 'ST'
        | 'SL'
        | 'TNINH'
        | 'TB'
        | 'TNG'
        | 'TH'
        | 'TTH'
        | 'TG'
        | 'TV'
        | 'TQ'
        | 'VL'
        | 'VP'
        | 'YB'
      )
    | null;
  district: string;
  ward_code: string;
  detail_address?: string | null;
  contact_name: string;
  contact_phone: string;
  id_default?: boolean | null;
  is_deleted?: boolean | null;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_trackings".
 */
export interface OrderTracking {
  id: number;
  begin_at: string;
  end_at: string;
  order_status: number | OrderStatus;
  order: number | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  discount_type: 'fixed_amount' | 'percentage';
  discount: number;
  start_date: string;
  end_date: string;
  description?: string | null;
  quantity: number;
  visible?: boolean | null;
  collected_quantity: number;
  current_use: number;
  minimum_price_to_use: number;
  collected_users?: (number | User)[] | null;
  used_users?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_details".
 */
export interface OrderDetail {
  id: number;
  quantity: number;
  price: number;
  discount?: number | null;
  variant?: (number | null) | Variant;
  order?: (number | null) | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  amount: number;
  payment_method: number | PaymentMethod;
  payment_status: number | PaymentStatus;
  order: number | Order;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment methods for orders that are used to group orders together
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_methods".
 */
export interface PaymentMethod {
  id: number;
  name: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The payment is not yet completed or is awaiting confirmation. This status usually indicates that the order has been received, but the payment process has not been finalized.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_statuses".
 */
export interface PaymentStatus {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bots that are used to interact with users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  bot_id: string;
  con_id: string;
  user: number | User;
  messages?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'product_discounts';
        value: number | ProductDiscount;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order_details';
        value: number | OrderDetail;
      } | null)
    | ({
        relationTo: 'order_trackings';
        value: number | OrderTracking;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'order_statuses';
        value: number | OrderStatus;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'sizes';
        value: number | Size;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'payment_methods';
        value: number | PaymentMethod;
      } | null)
    | ({
        relationTo: 'payment_statuses';
        value: number | PaymentStatus;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product_embeddings';
        value: number | ProductEmbedding;
      } | null)
    | ({
        relationTo: 'image_embeddings';
        value: number | ImageEmbedding;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  role?: T;
  date_of_birth?: T;
  phone_number?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  visible?: T;
  price?: T;
  overview?: T;
  material?: T;
  instruction?: T;
  slug?: T;
  sold_number?: T;
  category?: T;
  variants?: T;
  colors?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  product_discounts?: T;
  product_reviews?: T;
  product_embedding?: T;
  product_image_embeddings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  quantity?: T;
  size?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_discounts_select".
 */
export interface ProductDiscountsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  start_date?: T;
  end_date?: T;
  discount_type?: T;
  discount_value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  total_price?: T;
  total_discount?: T;
  final_price?: T;
  shipping_fee?: T;
  buyer?: T;
  current_status?: T;
  dilivery_address?: T;
  order_tracking?: T;
  used_coupon?: T;
  order_details?: T;
  order_trackings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_details_select".
 */
export interface OrderDetailsSelect<T extends boolean = true> {
  quantity?: T;
  price?: T;
  discount?: T;
  variant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_trackings_select".
 */
export interface OrderTrackingsSelect<T extends boolean = true> {
  begin_at?: T;
  end_at?: T;
  order_status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discount_type?: T;
  discount?: T;
  start_date?: T;
  end_date?: T;
  description?: T;
  quantity?: T;
  visible?: T;
  collected_quantity?: T;
  current_use?: T;
  minimum_price_to_use?: T;
  collected_users?: T;
  used_users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  comment?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  district?: T;
  ward_code?: T;
  detail_address?: T;
  contact_name?: T;
  contact_phone?: T;
  id_default?: T;
  is_deleted?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_statuses_select".
 */
export interface OrderStatusesSelect<T extends boolean = true> {
  status?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sizes_select".
 */
export interface SizesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  amount?: T;
  payment_method?: T;
  payment_status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_methods_select".
 */
export interface PaymentMethodsSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment_statuses_select".
 */
export interface PaymentStatusesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category_parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_embeddings_select".
 */
export interface ProductEmbeddingsSelect<T extends boolean = true> {
  product_id?: T;
  product_embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_embeddings_select".
 */
export interface ImageEmbeddingsSelect<T extends boolean = true> {
  product_id?: T;
  image_embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  bot_id?: T;
  con_id?: T;
  user?: T;
  messages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}